version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:v1.22.0-focal
    steps:
    - checkout
    - run:
        name: Run Tests
        command: |
          npm install
          npm test
    post-steps:
      - store_artifacts:
        path: /reports/